### ISSUE TITLE
Suivi du stock et todo

### ISSUE THREAD

**Issue by kazerlelutin** [kazerlelutin/hdc#11]
- [ ] Créer la table pour mon stock 
- [ ] créer la table de recette todo 
- [ ] la TODO peut avoir une date pour réaliser les recettes plus tard. 
- [ ] système de notification pour les rapelle
